spring.application.name=SpringSecurityExample

spring.security.user.name = joe
spring.security.user.password = joe1

spring.datasource.url = jdbc:postgresql://localhost:5432/
spring.datasource.username =
spring.datasource.password = 